FROM trsenna/vscodedevimages-php:7.4

# ENV DEBIAN_FRONTEND=noninteractive

# RUN sudo apt-get -y update --no-install-recommends \
#     && sudo apt-get -y install --no-install-recommends \
#     <your-package-list-here> \
#     && sudo apt-get autoremove -y \
#     && sudo apt-get clean -y
